### ISSUE TITLE
Answers Display Twice

### ISSUE THREAD

**Issue by mxwllndrsn** [mxwllndrsn/muoi#7]
Answers are displaying twice when card is flipped to reveal: 

![Screenshot from 2019-11-05 20-44-35](https://user-images.githubusercontent.com/753920/68269042-314e2080-000d-11ea-8b19-03eb452b907a.png)

**Comment by CB721** [comment]
It displays twice because it is displaying the alt information for the image.  Since it can't load an image (because there isn't any) it is displaying the text in it's place.

https://www.w3schools.com/tags/att_img_alt.asp

**Comment by mxwllndrsn** [comment]
Oh! That makes a lot of sense. Next time I will look at the code before opening an issue.
